In [ ]:
import torch
import pandas as pd
import matplotlib as plt
import numpy as np
print(torch.__version__)

2.4.1+cu121


##Introduction to Tensors

###Creating Tensors

Pytorch tensors are using 'torch.Tensor()' == https://pytorch.org/docs/stable/torch.html#tensors

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
#Dimension of the tensor
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[0,1]

tensor(8)

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

###Random Tensors

Why Random Tensors?
* Random Tensors are important bexause the way many NN learns is that they start tensors full of random numbers and then adjust those random numbers to better represent data

` Start with Random numbers -> Look at Data -> Update the Random Numbers -> Look at data -> Update Random Numbers `


In [ ]:
#Random Tensors
#Create a Random Tensor of size(3,4)
random_tensor = torch.rand(3, 4)
random_tensor



tensor([[0.4144, 0.9865, 0.5678, 0.6558],
        [0.7591, 0.6100, 0.7312, 0.0634],
        [0.3771, 0.0892, 0.6908, 0.4235]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.size()


torch.Size([3, 4])

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3, 224, 224)) # Color Cahnnels (RGB),Height, Width
random_image_size_tensor

tensor([[[0.3214, 0.9173, 0.7276,  ..., 0.4201, 0.4824, 0.1973],
         [0.4380, 0.7140, 0.7653,  ..., 0.5752, 0.4662, 0.2465],
         [0.8960, 0.4283, 0.7026,  ..., 0.9497, 0.0275, 0.2274],
         ...,
         [0.5780, 0.8816, 0.7771,  ..., 0.5102, 0.5972, 0.7352],
         [0.3584, 0.0078, 0.6580,  ..., 0.3640, 0.8422, 0.0021],
         [0.6164, 0.5967, 0.8299,  ..., 0.1311, 0.9477, 0.9578]],

        [[0.7847, 0.9972, 0.1522,  ..., 0.8692, 0.0263, 0.2204],
         [0.0131, 0.3587, 0.7428,  ..., 0.7710, 0.1577, 0.7858],
         [0.9464, 0.8686, 0.8702,  ..., 0.1652, 0.0825, 0.5119],
         ...,
         [0.9044, 0.3699, 0.2569,  ..., 0.4357, 0.1199, 0.2615],
         [0.4578, 0.1326, 0.7734,  ..., 0.4830, 0.3689, 0.3122],
         [0.3585, 0.2043, 0.0158,  ..., 0.6603, 0.2100, 0.1013]],

        [[0.3759, 0.1459, 0.1902,  ..., 0.0723, 0.9789, 0.4707],
         [0.5119, 0.8174, 0.9195,  ..., 0.7458, 0.4399, 0.0503],
         [0.4988, 0.8135, 0.1309,  ..., 0.3673, 0.8364, 0.

In [ ]:
random_image_size_tensor.shape

torch.Size([3, 224, 224])

In [ ]:
random_image_size_tensor.ndim

3

##Zeros and ones

In [ ]:
#Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
##Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
#Use torch.range()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
torch.arange(start = 0, end = 1000, step = 77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
#Creating Tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor Data types
**Note:** Tensor Datatypes is one of the 3 big issues you'll run into Pytorch & Deeplearning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None, #What dtype is your tensor(e.g. float32)
                               device= None,#What device is your tenosr on
                               requires_grad = False)#Whether or not to track gradients
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype #Default is Float32

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
int_32_tensor*float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on right device - to get device from a tensor, can use `tensor.device`


In [ ]:
#Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4722, 0.6834, 0.4543, 0.5365],
        [0.1824, 0.6974, 0.8797, 0.0425],
        [0.1185, 0.3916, 0.6753, 0.6237]])

In [ ]:
#Find out details about it
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4722, 0.6834, 0.4543, 0.5365],
        [0.1824, 0.6974, 0.8797, 0.0425],
        [0.1185, 0.3916, 0.6753, 0.6237]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


###Manipulating Tensors (Tensor Operation):

* Addition
* Substarction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

A tensor operation won't effect the main tensor unless it is declared

In [ ]:
#Create a Tensor and add 10
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
#Multiply it by 10
tensor*10

tensor([10, 20, 30])

In [ ]:
#Substract by 10
tensor-10

tensor([-9, -8, -7])

In [ ]:
#Tryout pytorch in built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)
torch.sub(tensor, 10)
torch.mul(tensor, 10)
torch.div(tensor,10)

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
#Division
tensor/10

tensor([0.1000, 0.2000, 0.3000])

###Matrix Multiplication

Two main ways of performing multiplication in nueral networks and deep learning:

1. Element-wise multiplication
2. Matrix Multiplication (Dot Products)


There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:
* `(3,2) @ (3,2) won't work`
* `(2,3) @ (3,2) will work`
* `(3,2) @ (2,3) will work`

2. Resulting matrix has the shape of the **outer dimensions**
* `(2,3) @ (3,2) --> (2,2)`
* `(3,2) @ (2,3) --> (3,3)`

In [ ]:
#Element-wise Multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
#Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
#Matrix Multiplication by hand
1*1+2*2+3*3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value+= tensor[i]*tensor[i]

print(value)

tensor(14)
CPU times: user 1.29 ms, sys: 1.04 ms, total: 2.33 ms
Wall time: 2.64 ms


In [ ]:
%time
torch.matmul(tensor,tensor)

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 7.87 µs


tensor(14)

In [ ]:
tensor @ tensor

tensor(14)

###One of the most common errors in DL: shape errors

In [ ]:
tensor_A = torch.tensor([[1,2],
                      [3,4],
                      [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.matmul(tensor_A, tensor_B)
#This will give error because shape is (2,3) @ (2,3)

To fix this issue we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.


In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


###Find the min, max, sum etc (tensor aggregation)

In [ ]:
#Create a tensor
X = torch.arange(0,100,10)
X

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
X.dtype

torch.int64

In [ ]:
#Find the min
torch.min(X), X.min()

(tensor(0), tensor(0))

In [ ]:
#Find the max
torch.max(X), X.max()

(tensor(90), tensor(90))

In [ ]:
#it won't take int64 or int32. It will only take float or complex dtype
torch.mean(X.type(torch.float32)), X.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
#Find the sum
torch.sum(X), X.sum()

(tensor(450), tensor(450))

## Finding the position min and max

In [ ]:
X

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#this will printout the the index/postion of the minimum value in a tensor
X.argmin()

tensor(0)

In [ ]:
X[0]

tensor(0)

In [ ]:
#this will printout the the index/postion of the maximum value in a tensor
X.argmax()

tensor(9)

In [ ]:
X[9]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Retuern a view of an input tensor of certain shape but keep the same memory as the original
* Stacking - combine multiple tensors on top of each other(vstack) or side by side(hstack)
* Squeeze - removes all 1 dimension from a tensor
* Unsqueeze - add a 1 dimesion to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
#Let's create a tensor
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#Changing z changes x(Because a view of a tensor shares the same memory as the original tensor)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
stacked = torch.stack([x,x,x,x], dim= 1)
stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
stacked_alter = torch.stack([x,x,x,x], dim= 0)
stacked_alter

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensors
print(f"Previosu tensor: {x_reshaped}")
print(f"Previosu shape: {x_reshaped.shape}")

#Remove extra Dimnesion from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previosu tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previosu shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze adds an extra dimension to a specific tensor
print(f"Previosu tensor: {x_squeezed}")
print(f"Previosu shape: {x_squeezed.shape}")

#Add an extra dimnesion with unsqueeze()
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


Previosu tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previosu shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute() - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,220,3)) #[Height, Width, Color]

#Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) #shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") #[color, height,width]

Previous shape: torch.Size([224, 220, 3])
New shape: torch.Size([3, 224, 220])


In [ ]:
x_original[0,0,0] = 728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

## Indexing (selecting data from tensors)

Indexing with Pytorchis similar to indexing with numpy

In [ ]:
#Creat a tensor
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#Let's index our new tensor
x[0] #First Bracket

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0] #Firs bracket's first bracket

tensor([1, 2, 3])

In [ ]:
x[0][0][0] #First bracket's First bracket's First element

tensor(1)

In [ ]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [ ]:
#You can also use ":" to slect "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values  of 0th and 1st dimension but only qst an 2nd dimesnions
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
#Get all values of the 0 dimension but only the 1st index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [ ]:
#Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
#Index on x to return 9
x[0,2,2]

tensor(9)

In [ ]:
#Index on x to return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

## Pytorch tensors & Numpy

Numpy is a popular scientific Python numerical library

And because of this, Pytorch has functionaity to interact with it.

* Data in Numpy, want in PyTorch tenosor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [ ]:
num_arr = np.arange(1.0,8.0)
print(f"Numpy array befor change: {num_arr}")
ten_arr = torch.from_numpy(num_arr) #Warning when converting into a tensor form numpty it changes in default float64 unless declared
print(f"Numpy array changed into a Tensor: {ten_arr}")
back_arr = (f"Tensor changed into a numpy array: {ten_arr.numpy()}")
print(back_arr)

Numpy array befor change: [1. 2. 3. 4. 5. 6. 7.]
Numpy array changed into a Tensor: tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)
Tensor changed into a numpy array: [1. 2. 3. 4. 5. 6. 7.]


In [ ]:
#Changing the value of numpy doesn't change the value in a tensor
num_arr = num_arr*2
num_arr, ten_arr

(array([ 2.,  4.,  6.,  8., 10., 12., 14.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor #If changed into numpy the dtype stays fixed

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#Change the tensor, what happens to `numpy tensor`?
tensor = tensor+1
tensor, numpy_tensor #It stays the same. Because both of them get different memory slots

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

##Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
#Creat two random tensors
random_Tensor_A = torch.rand(3,4)
random_Tensor_B = torch.rand(3,4)

print(random_Tensor_A)
print(random_Tensor_B)
print(random_Tensor_A == random_Tensor_B)

tensor([[0.3404, 0.8186, 0.2746, 0.0294],
        [0.8999, 0.6696, 0.4495, 0.8897],
        [0.0118, 0.0941, 0.3532, 0.8830]])
tensor([[0.9389, 0.8538, 0.5800, 0.2569],
        [0.7345, 0.6354, 0.2375, 0.9631],
        [0.0010, 0.8580, 0.2509, 0.8042]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#Let's make some random but reproducable tensors

#Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED) # This only works for each code block of line
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors on GPUs (and making faster computations)

GPUs = faster computations on numbers, thanks to CUDA + NVIDIA hardware +PyTorch working behind the scenes

## 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU )options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them


For 2,3 PyTorch + GPU drivers we need to do some set up and the best is to read documnetation from PyTOrch website

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Check for GPU access with PyTorch

In [ ]:
#Check for GPU access with PyTorch
torch.cuda.is_available()

False

In [ ]:
# Setup agnostic code
Device = "cuda" if torch.cuda.is_available() else "cpu"
Device

'cpu'

In [ ]:
# Count number of devices
torch.cuda.device_count( )

0

## 3. Putting tensors(and models) on the GPU

The reason we want  our tensors/models on the GPU is because using a GPU results in faster computations.

In [ ]:
#Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

#Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
#Move tensor to GPU(if available)
device = 'cpu'
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

## Moving back tensor backk to CPU

In [ ]:
#If tensor is on GPU, can't tranform tensor on GPU to NumPy
tensor_on_gpu.numpy()

array([1, 2, 3])

In [ ]:
#Fix
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

## Exercise 00

In [ ]:
#2
tensor = torch.rand(7,7)
tensor

tensor([[0.1587, 0.6542, 0.3278, 0.6532, 0.3958, 0.9147, 0.2036],
        [0.2018, 0.2018, 0.9497, 0.6666, 0.9811, 0.0874, 0.0041],
        [0.1088, 0.1637, 0.7025, 0.6790, 0.9155, 0.2418, 0.1591],
        [0.7653, 0.2979, 0.8035, 0.3813, 0.7860, 0.1115, 0.2477],
        [0.6524, 0.6057, 0.3725, 0.7980, 0.8399, 0.1374, 0.2331],
        [0.9578, 0.3313, 0.3227, 0.0162, 0.2137, 0.6249, 0.4340],
        [0.1371, 0.5117, 0.1585, 0.0758, 0.2247, 0.0624, 0.1816]])

In [ ]:
#3
new_tensor = torch.rand(1,7)
new_Transposed = new_tensor.T

print(torch.matmul(tensor, new_Transposed))


tensor([[2.1837],
        [1.9275],
        [1.7649],
        [2.0006],
        [2.1921],
        [1.6741],
        [0.8005]])


In [ ]:
#4
Random_seed = 13
torch.manual_seed(Random_seed)
tensor_with_seed = torch.rand(7,7)

torch.manual_seed(Random_seed)
new_tensor_with_seed = torch.rand(1,7)
new_tensor_with_seed_Transposed = new_tensor_with_seed.T

results = torch.matmul(tensor_with_seed, new_tensor_with_seed_Transposed)
print(results)

tensor([[1.3137],
        [1.3832],
        [0.7038],
        [1.3338],
        [0.9262],
        [1.0751],
        [1.1687]])


In [ ]:
results.min()


tensor(0.7038)

In [ ]:
results.max()

tensor(1.3832)

In [ ]:
#10
torch.manual_seed(7)
Ten = torch.rand(1,1,1,10)
Ten_squeezed = Ten.squeeze()
Ten_squeezed, Ten_squeezed.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))